import time

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from Pages.EditQuotePage import EditQuotePage
from Pages.LoginPage import LoginPage
from Pages.QuotePage import QuotePage
from Pages.LaborTravelPage import LaborTravelPage
from utilis.readProperties import ReadConfig
from utilis.customLogger import LogGen

class Test_SalesLaborTravel:

    # Software BaseUrl
    baseURL = ReadConfig.getApplicationURL()
    # UserNAME
    username = ReadConfig.getUseremail()
    # Password
    password = ReadConfig.getPassword()
    # Logger command
    logger = LogGen.loggen()

    laboritem = "LB0001"
    laboritem1 = "LB0002"
    laboritem2 = "LB0003"
    laboritem3 = "LB0004"
    laboritem4 = "LB0019"
    laboritem5 = "LB0025"
    laboritem6 = "LBAM2001"
    laboritem7 = "LBAMEMT4"
    travelitem = "LB1STR001"
    travelitem1 = "LB1OTR001"
    travelitem2 = "LB1ETR001"
    travelitem3 = "LB0007"
    travelitem4 = "LB0021"
    travelitem5 = "LB0022"
    travelitem6 = "LB0023"
    travelitem7 = "LB0024"


    def test_SalesLabor(self, setup):
        self.logger.info("*****Starting The Quote -> DocuSign Test*****")
        # Call the Browser Configuration
        self.logger.info("*****Call the Browser Configuration*****")
        self.driver = setup
        self.driver.implicitly_wait(10)
        # Open the Website URL
        self.logger.info("*****Open the Website URL*****")
        self.driver.get(self.baseURL)
        # Fit the browser screen
        self.logger.info("*****Fit the browser screen*****")
        self.driver.maximize_window()
        # Define LoginPage Driver
        self.logger.info("*****Define LoginPage Driver*****")
        self.lp = LoginPage(self.driver)
        # Fill the UserName field
        self.logger.info("*****Fill the UserName field*****")
        self.lp.setUserName(self.username)
        # Fill the Password field
        self.logger.info("*****Fill the Password field*****")
        self.lp.setPassword(self.password)
        # Click on the Signin Button
        self.logger.info("*****Click the Signin Button*****")
        self.lp.clickSignin()
        time.sleep(5)

        self.qp = QuotePage(self.driver)
        self.logger.info("*****Starting The Quote Page Test*****")
        self.logger.info("*****Click The Quote Tab*****")
        self.qp.clickCpqQuoteTab()
        time.sleep(5)
        self.logger.info("*****Click The Sales Quote*****")
        self.qp.SalesQuote()
        time.sleep(2)
        self.logger.info("*****Click the Edit Lines Button*****")
        self.qp.clickEditlines()
        time.sleep(7)
        self.logger.info("*****Switch to The Quote Line Editor*****")
        self.driver.switch_to.frame(0)

        self.logger.info("*****Starting The Quote Line Editor Test*****")
        self.ltp = LaborTravelPage(self.driver)
        windowsIDs = self.driver.window_handles
        parentwindowid = windowsIDs[0]
        childwindowid = windowsIDs[1]
        # childwindowid2 = windowsIDs[2]
        print(parentwindowid, childwindowid)
        self.logger.info("*****Click The Add Products Button *****")
        self.ltp.AddProdButton()
        time.sleep(3)
        # self.logger.info("*****Lookup a Sales Product*****")
        # self.ltp.SearchLabor(self.laboritem)
        # time.sleep(3)
        # self.logger.info("*****Search the Sales Product*****")
        # self.ltp.SearchButton()
        # time.sleep(3)
        # self.logger.info("*****Click The Apply Button*****")
        self.ltp.ApplyButton()
        time.sleep(3)
        self.driver.switch_to.window(childwindowid)
        time.sleep(4)
        self.ltp.doorProducts()
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(3)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(3)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Sales Product*****")
        # self.ltp.SearchLabor(self.laboritem2)
        # time.sleep(3)
        # self.logger.info("*****Search the Sales Product*****")
        # self.ltp.SearchButton()
        # time.sleep(3)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(3)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(2)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Sales Product*****")
        # self.ltp.SearchLabor(self.laboritem3)
        # time.sleep(3)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(3)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Travel Product*****")
        # self.ltp.SearchLabor(self.laboritem4)
        # time.sleep(3)
        # self.logger.info("*****Search the Travel Product****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Labor Product*****")
        # self.ltp.SearchLabor(self.laboritem5)
        # time.sleep(3)
        # self.logger.info("*****Search the Labor Product*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(5)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Labor Product*****")
        # self.ltp.SearchLabor(self.laboritem6)
        # time.sleep(3)
        # self.logger.info("*****Search the Labor Product*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(5)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Labor Product*****")
        # self.ltp.SearchLabor(self.laboritem7)
        # time.sleep(3)
        # self.logger.info("*****Search the Labor Product*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(5)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Sales Product*****")
        # self.ltp.SearchTravel(self.travelitem)
        # time.sleep(3)
        # self.logger.info("*****Search the Sales Product*****")
        # self.ltp.SearchButton()
        # time.sleep(3)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(3)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(3)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Sales Product*****")
        # self.ltp.SearchTravel(self.travelitem1)
        # time.sleep(3)
        # self.logger.info("*****Search the Sales Product*****")
        # self.ltp.SearchButton()
        # time.sleep(3)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(3)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(2)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Sales Product*****")
        # self.ltp.SearchTravel(self.travelitem2)
        # time.sleep(3)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(3)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Travel Product*****")
        # self.ltp.SearchTravel(self.travelitem3)
        # time.sleep(3)
        # self.logger.info("*****Search the Travel Product****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Labor Product*****")
        # self.ltp.SearchTravel(self.travelitem4)
        # time.sleep(3)
        # self.logger.info("*****Search the Labor Product*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(5)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Labor Product*****")
        # self.ltp.SearchTravel(self.travelitem5)
        # time.sleep(3)
        # self.logger.info("*****Search the Labor Product*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(5)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Labor Product*****")
        # self.ltp.SearchTravel(self.travelitem6)
        # time.sleep(3)
        # self.logger.info("*****Search the Labor Product*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(5)
        # self.logger.info("*****Click The Add Products Button *****")
        # self.ltp.AddProdButton()
        # time.sleep(3)
        # self.logger.info("*****Lookup a Labor Product*****")
        # self.ltp.SearchTravel(self.travelitem7)
        # time.sleep(3)
        # self.logger.info("*****Search the Labor Product*****")
        # self.ltp.SearchButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Product Checkbox*****")
        # self.ltp.ProductCheckbox()
        # time.sleep(2)
        # self.logger.info("*****Click the Select Button to Add the Product to the QLE*****")
        # self.ltp.SelectButton()
        # time.sleep(5)
        # self.logger.info("*****Click the Save Button*****")
        # self.ltp.SaveButton()
        time.sleep(5)



        self.logger.info("*****Sales Labor & Travel Test Completed*****")
        self.driver.save_screenshot("/Users/oluwasegun.ojeyinka/PycharmProjects/ProjectHorizon/Screenshots/SalLaborTravelpage.png")
        self.driver.quit()
